default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: bone_sound_dev

test:
  <<: *default
  database: bone_sound_test

production:
  <<: *default
  database: production_db_name
